# Generated by Django 4.2.6 on 2023-10-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='cocnversation',
            new_name='conversation',
        ),
    ]
